### PR TITLE
jupyterbook-latex 0.3.1 (alternate)

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Notes
- quick attempt at an alternative to #3, works locally :crossed_fingers: 
- might help https://github.com/conda-forge/jupyter-book-feedstock/pull/5

### CODE REVIEW

**Comment by bollwyvl** [comment]
Might help unblock https://github.com/conda-forge/jupyter-book-feedstock/pull/5

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge/jupyterbook-latex looks good! Will leave open a sec for comment...

**Comment by AakashGfude** [comment]
Thanks, @bollwyvl . Happy for you to merge this one.

**Review by AakashGfude — APPROVED** [review]

**Pull request merged**
